-- ============================================
-- VOGUEX COMPLETE DATABASE SETUP
-- ============================================
-- Run this ONCE in Supabase SQL Editor
-- This sets up everything needed for the app

-- ============================================
-- 0. CLEAN UP - Drop all existing policies first
-- ============================================

-- This ensures no conflicts when re-running the script
DO $$ 
DECLARE
    r RECORD;
BEGIN
    -- Drop all policies on all tables
    FOR r IN (
        SELECT schemaname, tablename, policyname 
        FROM pg_policies 
        WHERE schemaname = 'public'
    ) LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON %I.%I', r.policyname, r.schemaname, r.tablename);
    END LOOP;
    
    -- Drop all policies on storage.objects
    FOR r IN (
        SELECT policyname 
        FROM pg_policies 
        WHERE schemaname = 'storage' AND tablename = 'objects'
    ) LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON storage.objects', r.policyname);
    END LOOP;
END $$;

-- ============================================
-- 1. CREATE TABLES
-- ============================================

-- Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    username TEXT UNIQUE,
    full_name TEXT,
    avatar_url TEXT,
    website TEXT,
    email TEXT,
    date_of_birth DATE,
    CONSTRAINT username_length CHECK (char_length(username) >= 3)
);

-- Ensure columns exist (in case table already existed without them)
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS username TEXT UNIQUE;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS website TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS date_of_birth DATE;

-- Posts Table
CREATE TABLE IF NOT EXISTS public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    content TEXT,
    image_url TEXT,
    video_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Comments Table
CREATE TABLE IF NOT EXISTS public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES public.posts ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES auth.users NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Likes Table
CREATE TABLE IF NOT EXISTS public.likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES public.posts ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES auth.users NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(post_id, user_id)
);

-- Messages Table
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id UUID REFERENCES auth.users NOT NULL,
    receiver_id UUID REFERENCES auth.users NOT NULL,
    content TEXT NOT NULL,
    read BOOLEAN DEFAULT FALSE,
    story_id BIGINT REFERENCES public.stories(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add story_id column if it doesn't exist
ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS story_id BIGINT REFERENCES public.stories(id) ON DELETE SET NULL;

-- Verified Users Table
CREATE TABLE IF NOT EXISTS public.verified_users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Followers Table
CREATE TABLE IF NOT EXISTS public.followers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id UUID REFERENCES auth.users NOT NULL,
    following_id UUID REFERENCES auth.users NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(follower_id, following_id),
    CHECK (follower_id != following_id)
);

-- Stories Table (for 24-hour stories feature)
CREATE TABLE IF NOT EXISTS public.stories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) NOT NULL,
    media_url TEXT NOT NULL,
    media_type TEXT DEFAULT 'image' CHECK (media_type IN ('image', 'video')),
    viewers UUID[] DEFAULT '{}',
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Story Views Table (for proper view tracking)
CREATE TABLE IF NOT EXISTS public.story_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id BIGINT REFERENCES public.stories(id) ON DELETE CASCADE NOT NULL,
    viewer_id UUID REFERENCES auth.users NOT NULL,
    viewed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(story_id, viewer_id)
);

-- ============================================
-- 2. ENABLE ROW LEVEL SECURITY
-- ============================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.verified_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.followers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.story_views ENABLE ROW LEVEL SECURITY;

-- ============================================
-- 3. DROP EXISTING POLICIES (IF ANY)
-- ============================================

-- Drop ALL existing policies to avoid conflicts
DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.profiles;
DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles;

DROP POLICY IF EXISTS "Public posts are viewable by everyone" ON public.posts;
DROP POLICY IF EXISTS "Users can insert their own posts" ON public.posts;
DROP POLICY IF EXISTS "Users can update their own posts" ON public.posts;
DROP POLICY IF EXISTS "Users can delete their own posts" ON public.posts;

DROP POLICY IF EXISTS "Comments are viewable by everyone" ON public.comments;
DROP POLICY IF EXISTS "Users can insert their own comments" ON public.comments;
DROP POLICY IF EXISTS "Users can delete their own comments" ON public.comments;

DROP POLICY IF EXISTS "Likes are viewable by everyone" ON public.likes;
DROP POLICY IF EXISTS "Users can insert their own likes" ON public.likes;
DROP POLICY IF EXISTS "Users can delete their own likes" ON public.likes;

DROP POLICY IF EXISTS "Users can view their own messages" ON public.messages;
DROP POLICY IF EXISTS "Users can send messages" ON public.messages;
DROP POLICY IF EXISTS "Users can update their received messages" ON public.messages;

DROP POLICY IF EXISTS "Verified users are viewable by everyone" ON public.verified_users;
DROP POLICY IF EXISTS "Authenticated users can add verified users" ON public.verified_users;

DROP POLICY IF EXISTS "Followers are viewable by everyone" ON public.followers;
DROP POLICY IF EXISTS "Users can follow others" ON public.followers;
DROP POLICY IF EXISTS "Users can unfollow others" ON public.followers;
DROP POLICY IF EXISTS "Verified users can add followers to any account" ON public.followers;
DROP POLICY IF EXISTS "Verified users can remove followers from any account" ON public.followers;

-- ============================================
-- 4. CREATE POLICIES
-- ============================================

-- Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone"
    ON public.profiles FOR SELECT
    USING (true);

CREATE POLICY "Users can insert their own profile"
    ON public.profiles FOR INSERT
    WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update their own profile"
    ON public.profiles FOR UPDATE
    USING (auth.uid() = id);

-- Posts Policies
CREATE POLICY "Public posts are viewable by everyone"
    ON public.posts FOR SELECT
    USING (true);

CREATE POLICY "Users can insert their own posts"
    ON public.posts FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own posts"
    ON public.posts FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own posts"
    ON public.posts FOR DELETE
    USING (auth.uid() = user_id);

-- Comments Policies
CREATE POLICY "Comments are viewable by everyone"
    ON public.comments FOR SELECT
    USING (true);

CREATE POLICY "Users can insert their own comments"
    ON public.comments FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own comments"
    ON public.comments FOR DELETE
    USING (auth.uid() = user_id);

-- Likes Policies
CREATE POLICY "Likes are viewable by everyone"
    ON public.likes FOR SELECT
    USING (true);

CREATE POLICY "Users can insert their own likes"
    ON public.likes FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own likes"
    ON public.likes FOR DELETE
    USING (auth.uid() = user_id);

-- Messages Policies
CREATE POLICY "Users can view their own messages"
    ON public.messages FOR SELECT
    USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

CREATE POLICY "Users can send messages"
    ON public.messages FOR INSERT
    WITH CHECK (auth.uid() = sender_id);

CREATE POLICY "Users can update their received messages"
    ON public.messages FOR UPDATE
    USING (auth.uid() = receiver_id);

-- Verified Users Policies
CREATE POLICY "Verified users are viewable by everyone"
    ON public.verified_users FOR SELECT
    USING (true);

CREATE POLICY "Authenticated users can add verified users"
    ON public.verified_users FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');

-- Followers Policies
CREATE POLICY "Followers are viewable by everyone"
    ON public.followers FOR SELECT
    USING (true);

CREATE POLICY "Users can follow others"
    ON public.followers FOR INSERT
    WITH CHECK (auth.uid() = follower_id);

CREATE POLICY "Users can unfollow others"
    ON public.followers FOR DELETE
    USING (auth.uid() = follower_id);

-- Admin Policies for Verified Users
DROP POLICY IF EXISTS "Verified users can add followers to any account" ON public.followers;
DROP POLICY IF EXISTS "Verified users can remove followers from any account" ON public.followers;

CREATE POLICY "Verified users can add followers to any account"
    ON public.followers FOR INSERT
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.verified_users vu
            JOIN public.profiles p ON p.username = vu.username
            WHERE p.id = auth.uid()
        )
    );

CREATE POLICY "Verified users can remove followers from any account"
    ON public.followers FOR DELETE
    USING (
        EXISTS (
            SELECT 1 FROM public.verified_users vu
            JOIN public.profiles p ON p.username = vu.username
            WHERE p.id = auth.uid()
        )
    );

-- Stories Policies (Only show stories from people you follow or your own)
DROP POLICY IF EXISTS "Stories are viewable by followers" ON public.stories;
DROP POLICY IF EXISTS "Users can create their own stories" ON public.stories;
DROP POLICY IF EXISTS "Users can update their own stories" ON public.stories;
DROP POLICY IF EXISTS "Users can delete their own stories" ON public.stories;

CREATE POLICY "Stories are viewable by followers"
    ON public.stories FOR SELECT
    USING (
        auth.uid() = user_id OR -- Own stories
        EXISTS ( -- Stories from people you follow
            SELECT 1 FROM public.followers
            WHERE follower_id = auth.uid() AND following_id = user_id
        )
    );

CREATE POLICY "Users can create their own stories"
    ON public.stories FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own stories"
    ON public.stories FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own stories"
    ON public.stories FOR DELETE
    USING (auth.uid() = user_id);

-- Story Views Policies
DROP POLICY IF EXISTS "Users can view story views" ON public.story_views;
DROP POLICY IF EXISTS "Users can add story views" ON public.story_views;

CREATE POLICY "Users can view story views"
    ON public.story_views FOR SELECT
    USING (
        viewer_id = auth.uid() OR -- Own views
        EXISTS ( -- Views on own stories
            SELECT 1 FROM public.stories
            WHERE stories.id = story_id AND stories.user_id = auth.uid()
        )
    );

CREATE POLICY "Users can add story views"
    ON public.story_views FOR INSERT
    WITH CHECK (auth.uid() = viewer_id);

-- ============================================
-- 5. CREATE INDEXES FOR PERFORMANCE
-- ============================================

CREATE INDEX IF NOT EXISTS idx_posts_user_id ON public.posts(user_id);
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON public.posts(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_comments_post_id ON public.comments(post_id);
CREATE INDEX IF NOT EXISTS idx_comments_user_id ON public.comments(user_id);
CREATE INDEX IF NOT EXISTS idx_comments_created_at ON public.comments(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_likes_post_id ON public.likes(post_id);
CREATE INDEX IF NOT EXISTS idx_likes_user_id ON public.likes(user_id);

CREATE INDEX IF NOT EXISTS idx_messages_sender ON public.messages(sender_id);
CREATE INDEX IF NOT EXISTS idx_messages_receiver ON public.messages(receiver_id);
CREATE INDEX IF NOT EXISTS idx_messages_created ON public.messages(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_profiles_username ON public.profiles(username);

CREATE INDEX IF NOT EXISTS idx_followers_follower ON public.followers(follower_id);
CREATE INDEX IF NOT EXISTS idx_followers_following ON public.followers(following_id);

CREATE INDEX IF NOT EXISTS idx_stories_user_id ON public.stories(user_id);
CREATE INDEX IF NOT EXISTS idx_stories_expires_at ON public.stories(expires_at);
CREATE INDEX IF NOT EXISTS idx_stories_created_at ON public.stories(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_story_views_story_id ON public.story_views(story_id);
CREATE INDEX IF NOT EXISTS idx_story_views_viewer_id ON public.story_views(viewer_id);

CREATE INDEX IF NOT EXISTS idx_messages_story_id ON public.messages(story_id);

-- ============================================
-- 6. CREATE TRIGGER FUNCTION FOR NEW USERS
-- ============================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, email, username, full_name, avatar_url)
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(
            NEW.raw_user_meta_data->>'username',
            SPLIT_PART(NEW.email, '@', 1),
            'user_' || SUBSTRING(NEW.id::text, 1, 8)
        ),
        COALESCE(
            NEW.raw_user_meta_data->>'full_name',
            SPLIT_PART(NEW.email, '@', 1),
            'User'
        ),
        COALESCE(
            NEW.raw_user_meta_data->>'avatar_url',
            '/download.png'
        )
    )
    ON CONFLICT (id) DO UPDATE
    SET 
        email = EXCLUDED.email,
        username = COALESCE(NULLIF(profiles.username, ''), EXCLUDED.username),
        full_name = COALESCE(NULLIF(profiles.full_name, ''), EXCLUDED.full_name),
        avatar_url = COALESCE(NULLIF(profiles.avatar_url, ''), EXCLUDED.avatar_url);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================
-- 7. CREATE TRIGGER FOR NEW USERS
-- ============================================

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================
-- 8. FIX EXISTING USERS (CREATE PROFILES)
-- ============================================

INSERT INTO public.profiles (id, email, username, full_name, avatar_url)
SELECT 
    u.id,
    u.email,
    COALESCE(
        u.raw_user_meta_data->>'username',
        SPLIT_PART(u.email, '@', 1),
        'user_' || SUBSTRING(u.id::text, 1, 8)
    ) as username,
    COALESCE(
        u.raw_user_meta_data->>'full_name',
        SPLIT_PART(u.email, '@', 1),
        'User'
    ) as full_name,
    COALESCE(
        u.raw_user_meta_data->>'avatar_url',
        '/download.png'
    ) as avatar_url
FROM auth.users u
WHERE u.id NOT IN (SELECT id FROM public.profiles)
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- 9. FIX NULL USERNAMES AND NAMES
-- ============================================

UPDATE public.profiles
SET username = COALESCE(
    NULLIF(username, ''),
    SPLIT_PART(email, '@', 1),
    'user_' || SUBSTRING(id::text, 1, 8)
)
WHERE username IS NULL OR username = '';

UPDATE public.profiles
SET full_name = COALESCE(
    NULLIF(full_name, ''),
    SPLIT_PART(email, '@', 1),
    'User'
)
WHERE full_name IS NULL OR full_name = '';

UPDATE public.profiles
SET avatar_url = '/download.png'
WHERE avatar_url IS NULL OR avatar_url = '';

-- ============================================
-- 10. CREATE STORAGE BUCKETS
-- ============================================

-- Create the avatars bucket for profile photos
INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Create the images bucket for post images
INSERT INTO storage.buckets (id, name, public)
VALUES ('images', 'images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Create the videos bucket for post videos
INSERT INTO storage.buckets (id, name, public)
VALUES ('videos', 'videos', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Drop ALL existing storage policies to avoid conflicts
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload images" ON storage.objects;
DROP POLICY IF EXISTS "Users can update their own images" ON storage.objects;
DROP POLICY IF EXISTS "Users can delete their own images" ON storage.objects;

DROP POLICY IF EXISTS "Public avatar access" ON storage.objects;
DROP POLICY IF EXISTS "Users can upload avatars" ON storage.objects;
DROP POLICY IF EXISTS "Users can update own avatars" ON storage.objects;
DROP POLICY IF EXISTS "Users can delete own avatars" ON storage.objects;

DROP POLICY IF EXISTS "Public video access" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload videos" ON storage.objects;
DROP POLICY IF EXISTS "Users can update their own videos" ON storage.objects;
DROP POLICY IF EXISTS "Users can delete their own videos" ON storage.objects;

DROP POLICY IF EXISTS "Stories Public View" ON storage.objects;
DROP POLICY IF EXISTS "Stories Auth Upload" ON storage.objects;
DROP POLICY IF EXISTS "Stories Owner Update" ON storage.objects;
DROP POLICY IF EXISTS "Stories Owner Delete" ON storage.objects;

-- ============================================
-- AVATARS BUCKET POLICIES (Profile Photos)
-- ============================================

-- Allow public access to view avatars
CREATE POLICY "Public avatar access"
ON storage.objects FOR SELECT
USING (bucket_id = 'avatars');

-- Allow authenticated users to upload avatars
CREATE POLICY "Users can upload avatars"
ON storage.objects FOR INSERT
WITH CHECK (
    bucket_id = 'avatars' 
    AND auth.role() = 'authenticated'
);

-- Allow users to update their own avatars
CREATE POLICY "Users can update own avatars"
ON storage.objects FOR UPDATE
USING (
    bucket_id = 'avatars' 
    AND auth.uid()::text = (storage.foldername(name))[1]
);

-- Allow users to delete their own avatars
CREATE POLICY "Users can delete own avatars"
ON storage.objects FOR DELETE
USING (
    bucket_id = 'avatars' 
    AND auth.uid()::text = (storage.foldername(name))[1]
);

-- ============================================
-- IMAGES BUCKET POLICIES (Post Images)
-- ============================================

-- Allow public access to view post images
CREATE POLICY "Public Access"
ON storage.objects FOR SELECT
USING (bucket_id = 'images');

-- Allow authenticated users to upload post images
CREATE POLICY "Authenticated users can upload images"
ON storage.objects FOR INSERT
WITH CHECK (
    bucket_id = 'images' 
    AND auth.role() = 'authenticated'
);

-- Allow users to update their own post images
CREATE POLICY "Users can update their own images"
ON storage.objects FOR UPDATE
USING (
    bucket_id = 'images' 
    AND auth.uid()::text = (storage.foldername(name))[1]
);

-- Allow users to delete their own post images
CREATE POLICY "Users can delete their own images"
ON storage.objects FOR DELETE
USING (
    bucket_id = 'images' 
    AND auth.uid()::text = (storage.foldername(name))[1]
);

-- ============================================
-- VIDEOS BUCKET POLICIES (Post Videos)
-- ============================================

-- Allow public access to view post videos
CREATE POLICY "Public video access"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'videos');

-- Allow authenticated users to upload post videos
CREATE POLICY "Authenticated users can upload videos"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'videos');

-- Allow users to update their own post videos
CREATE POLICY "Users can update their own videos"
ON storage.objects FOR UPDATE
TO authenticated
USING (bucket_id = 'videos');

-- Allow users to delete their own post videos
CREATE POLICY "Users can delete their own videos"
ON storage.objects FOR DELETE
TO authenticated
USING (bucket_id = 'videos');

-- ============================================
-- 11. ADD VERIFIED USERS (OPTIONAL)
-- ============================================

-- Add your verified users here
-- Example:
-- INSERT INTO public.verified_users (username) 
-- VALUES ('prakhar69135')
-- ON CONFLICT (username) DO NOTHING;

-- ============================================
-- 12. VERIFICATION QUERIES
-- ============================================

-- Check all tables exist
SELECT 
    'Tables Created' as status,
    COUNT(*) as count
FROM information_schema.tables 
WHERE table_schema = 'public' 
AND table_name IN ('profiles', 'posts', 'comments', 'likes', 'messages', 'verified_users');

-- Check all users have profiles
SELECT 
    'Users' as type,
    COUNT(*) as count
FROM auth.users
UNION ALL
SELECT 
    'Profiles' as type,
    COUNT(*) as count
FROM public.profiles
UNION ALL
SELECT 
    'Posts' as type,
    COUNT(*) as count
FROM public.posts
UNION ALL
SELECT 
    'Comments' as type,
    COUNT(*) as count
FROM public.comments
UNION ALL
SELECT 
    'Likes' as type,
    COUNT(*) as count
FROM public.likes
UNION ALL
SELECT 
    'Messages' as type,
    COUNT(*) as count
FROM public.messages
UNION ALL
SELECT 
    'Verified Users' as type,
    COUNT(*) as count
FROM public.verified_users;

-- Check for users without profiles
SELECT 
    'Users WITHOUT Profiles' as check_name,
    COUNT(*) as count
FROM auth.users u
LEFT JOIN public.profiles p ON u.id = p.id
WHERE p.id IS NULL;

-- Check for profiles with NULL usernames
SELECT 
    'Profiles with NULL username' as check_name,
    COUNT(*) as count
FROM public.profiles
WHERE username IS NULL OR username = '';

-- Show sample data
SELECT 
    'Sample Profiles' as info,
    id,
    email,
    username,
    full_name,
    CASE 
        WHEN username IS NULL OR username = '' THEN '❌ Missing Username'
        WHEN full_name IS NULL OR full_name = '' THEN '❌ Missing Full Name'
        ELSE '✅ Complete'
    END as status
FROM public.profiles
LIMIT 5;

-- 2. Enable RLS on user_presence
-- 2. Enable RLS on user_presence
-- 2. Enable RLS on user_presence
-- ============================================
-- MESSAGING FEATURES SETUP
-- Adds: User Presence, Typing Indicators, Unread Counts
-- ============================================

-- 1. Create user presence table
CREATE TABLE IF NOT EXISTS public.user_presence (
    user_id UUID PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
    is_online BOOLEAN DEFAULT FALSE,
    last_seen TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Enable RLS on user_presence
ALTER TABLE public.user_presence ENABLE ROW LEVEL SECURITY;

-- 3. Drop ALL existing policies to avoid conflicts
DROP POLICY IF EXISTS "Anyone can view presence" ON public.user_presence;
DROP POLICY IF EXISTS "Users can insert own presence" ON public.user_presence;
DROP POLICY IF EXISTS "Users can update own presence" ON public.user_presence;
DROP POLICY IF EXISTS "Users can delete own presence" ON public.user_presence;

-- 4. Create policies for user_presence
CREATE POLICY "Anyone can view presence" 
ON public.user_presence FOR SELECT 
USING (true);

CREATE POLICY "Users can insert own presence" 
ON public.user_presence FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own presence" 
ON public.user_presence FOR UPDATE 
USING (auth.uid() = user_id);

-- 5. Create function to update presence timestamp
CREATE OR REPLACE FUNCTION update_presence_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 6. Create trigger for presence timestamp
DROP TRIGGER IF EXISTS update_presence_timestamp_trigger ON public.user_presence;
CREATE TRIGGER update_presence_timestamp_trigger
BEFORE UPDATE ON public.user_presence
FOR EACH ROW
EXECUTE FUNCTION update_presence_timestamp();

-- 7. Create index for performance
CREATE INDEX IF NOT EXISTS idx_user_presence_online ON public.user_presence(is_online);
CREATE INDEX IF NOT EXISTS idx_user_presence_last_seen ON public.user_presence(last_seen DESC);

-- 8. Initialize presence for existing users
INSERT INTO public.user_presence (user_id, is_online, last_seen)
SELECT id, false, NOW()
FROM auth.users
WHERE id NOT IN (SELECT user_id FROM public.user_presence)
ON CONFLICT (user_id) DO NOTHING;

-- 9. Verify setup
SELECT 'User presence table created successfully!' as status;
SELECT COUNT(*) as presence_records FROM public.user_presence;

-- 10. Show table structure
SELECT 
    column_name, 
    data_type,
    is_nullable
FROM information_schema.columns 
WHERE table_name = 'user_presence' 
AND table_schema = 'public'
ORDER BY ordinal_position;


-- ============================================
-- STORIES BUCKET SETUP (For Story Uploads)
-- ============================================

-- Ensure Storage Bucket Exists (Force Creation)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('stories', 'stories', true, 52428800, ARRAY['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'video/mp4', 'video/webm', 'video/quicktime'])
ON CONFLICT (id) DO UPDATE SET 
    public = true,
    file_size_limit = 52428800,
    allowed_mime_types = ARRAY['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'video/mp4', 'video/webm', 'video/quicktime'];

-- Create Storage Policies (already dropped above)
-- Allow anyone to view stories
CREATE POLICY "Stories Public View"
ON storage.objects FOR SELECT
TO public
USING ( bucket_id = 'stories' );

-- Allow authenticated users to upload stories
CREATE POLICY "Stories Auth Upload"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'stories' );

-- Allow users to update their own stories
CREATE POLICY "Stories Owner Update"
ON storage.objects FOR UPDATE
TO authenticated
USING ( bucket_id = 'stories' );

-- Allow users to delete their own stories
CREATE POLICY "Stories Owner Delete"
ON storage.objects FOR DELETE
TO authenticated
USING ( bucket_id = 'stories' );

SELECT 'DONE SETUP: Stories bucket and all policies (SELECT, INSERT, UPDATE, DELETE) enforced.' as message;

-- ============================================
-- VERIFICATION: Check all storage buckets exist
-- ============================================
SELECT id, name, public, file_size_limit FROM storage.buckets 
WHERE id IN ('avatars', 'images', 'videos', 'stories');
